base_url = "https://docs.worldwidetelescope.org/tour-authoring-guide/1/"
title = "WWT Tour Authoring Guide"
description = "Creating AAS WorldWide Telescope tours."
theme = "wwtguide"
highlight_code = true

[extra]
github_base = "https://github.com/WorldWideTelescope/worldwide-telescope-tour-authoring-guide"
google_analytics_id = "G-D1J49XX0CV"
